### ISSUE TITLE
[procfwk].[CheckForBlockedPipelines] has an unresolved reference to object [procfwk].[CurrentExecution].[AdfPipelineRunId]

### ISSUE THREAD

**Issue by syntrixsystems** [mrpaulandrew/procfwk#106]
**Describe the bug**
MetadataDB Build Failure:

Severity	Code	Description	Project	File	Line	Suppression State
Error		SQL71501: Procedure: [procfwk].[CheckForBlockedPipelines] has an unresolved reference to object [procfwk].[CurrentExecution].[AdfPipelineRunId].	MetadataDB	C:\Users\doubl\OneDrive\Documents\Work\NTT\ADF\procfwk-master\MetadataDB\procfwk\Stored Procedures\CheckForBlockedPipelines.sql	33	

**Affected services**
Which resource within the processing framework does this affect?

* SQL Database

**To Reproduce**
Build MetadataDB

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by smo-ceteris** [comment]
Wrong naming, should be PipelineRunId I guess.

**Comment by JohnTheBeaver** [comment]
The proposed solution of @smo-ceteris works!

**Comment by PRITESHPATEL2205** [comment]
I agree with JohnTheBeaver, the proposed solution of @smo-ceteris works! Just rename change the field "AdfPipelineRunId" in the select sql to [PipelineRunId]. After the change, MetadataDB should build successfully.

**Comment by mrpaulandrew** [comment]
Thanks for the feedback, this has already been corrected in the 'develop' branch and will be resolved in the next release.
