### ISSUE TITLE
Question: Is there a way to migrate pre-existing ADF to this framework?

### ISSUE THREAD

**Issue by kenny-bui-slalom** [mrpaulandrew/procfwk#98]
as per title, is there a way to migrate pre-existing ADF to this framework?

I seem to recall hearing/reading this was possible with a tool but I cannot find that information.

**Comment by BeneHa** [comment]
There is some information on this here - it will get you started populating the metadata:
https://mrpaulandrew.github.io/procfwk/applytoexistingadfs

**Comment by kenny-bui-slalom** [comment]
awesome thank you
